/**
 * mutation variables which is used inside vuex store
 */

export const REFRESH_APP_LIST = 'REFRESH_APP_LIST';
export const REFRESH_MY_APP_LIST = 'REFRESH_MY_APP_LIST';
export const REFRESH_ENV_LIST = 'REFRESH_ENV_LIST';
export const REFRESH_ENV_ACTIVE_LIST = 'REFRESH_ENV_ACTIVE_LIST';
export const REFRESH_RELEASE_GROUP_LIST = 'REFRESH_RELEASE_GROUP_LIST';
export const REFRESH_PROMPT_MESSAGE = 'REFRESH_PROMPT_MESSAGE';
export const REFRESH_IMAGE_LIST = 'REFRESH_IMAGE_LIST';
export const REFRESH_VALUABLE_IMAGE_LIST = 'REFRESH_VALUABLE_IMAGE_LIST';
export const REFRESH_GROUP_JOB_STATUS = 'REFRESH_GROUP_JOB_STATUS';
export const REFRESH_GROUP_INSTANCE_LIST = 'REFRESH_GROUP_INSTANCE_LIST';
export const REFRESH_APP_INSTANCE_LIST = 'REFRESH_APP_INSTANCE_LIST';
export const REFRESH_CURRENT_SITE = 'REFRESH_CURRENT_SITE';
export const REFRESH_CURRENT_GROUP = 'REFRESH_CURRENT_GROUP';
export const REFRESH_CURRENT_ENV = 'REFRESH_CURRENT_ENV';
export const REFRESH_CURRENT_APP_ID = 'REFRESH_CURRENT_APP_ID';
export const REFRESH_ORG_LIST = 'REFRESH_ORG_LIST';
export const REFRESH_IMAGES_BY_PAGE = 'REFRESH_IMAGES_BY_PAGE';
export const REFRESH_APPS_BY_PAGE = 'REFRESH_APPS_BY_PAGE';
export const REFRESH_RELEASE_HISTORY_BY_PAGE = 'REFRESH_RELEASE_HISTORY_BY_PAGE';
export const REFRESH_RELEASE_RECORD_BY_PAGE = 'REFRESH_RELEASE_RECORD_BY_PAGE';
export const REFRESH_RELEASE_TYPE_LIST = 'REFRESH_RELEASE_TYPE_LIST';
export const REFRESH_RELEASE_LOG = 'REFRESH_RELEASE_LOG';
export const REFRESH_CONTAINER_LOG = 'REFRESH_CONTAINER_LOG';
export const REFRESH_RELEASE_STATUS = 'REFRESH_RELEASE_STATUS';
export const REFRESH_APP_QUOTAS = 'REFRESH_APP_QUOTAS';
export const REFRESH_APP_QUOTA_STATUS = 'REFRESH_APP_QUOTA_STATUS';
export const REFRESH_AUDIT_LOGS_BY_PAGE = 'REFRESH_AUDIT_LOGS_BY_PAGE';
export const REFRESH_APPLY_LIST = 'REFRESH_APPLY_LIST';
export const REFRESH_USER_LIST = 'REFRESH_USER_LIST';
export const REFRESH_ENV_ZONES = 'REFRESH_ENV_ZONES';
export const REFRESH_IP_LIST = 'REFRESH_IP_LIST';
export const REFRESH_RESOURCE_LIST = 'REFRESH_RESOURCE_LIST';
export const REFRESH_RESOURCE_QUOTA_STATUS = 'REFRESH_RESOURCE_QUOTA_STATUS';
export const REFRESH_AVAILABLE_RESOURCES = 'REFRESH_AVAILABLE_RESOURCES';
export const REFRESH_HOST_INSTANCE_LIST = 'REFRESH_HOST_INSTANCE_LIST';
export const REFRESH_CLOUD_INSTANCES_BY_PAGE = 'REFRESH_CLOUD_INSTANCES_BY_PAGE';
export const REFRESH_CLOUD_INSTANCE_STATUS = 'REFRESH_CLOUD_INSTANCE_STATUS';
export const REFRESH_CLOUD_INSTANCE_LOG = 'REFRESH_CLOUD_INSTANCE_LOG';
export const REFRESH_INSTANCE_COUNT_INFO = 'REFRESH_INSTANCE_COUNT_INFO';
export const REFRESH_APP_SETTING = 'REFRESH_APP_SETTING';
export const REFRESH_EXEC_COMMAND_RESULT = 'REFRESH_EXEC_COMMAND_RESULT';
export const REFRESH_DNS_LIST = 'REFRESH_DNS_LIST';